version: '3.8'

services:
  ccdi-rest-adapter:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - GRAPHQL_URL=https://your-graphql-api.com/graphql
      - REDIS_URL=redis://redis:6379
      - PORT=3000
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
